### ISSUE TITLE
ERROR: "You probably have selected the wrong camera"

### ISSUE THREAD

**Issue by dkoukoul** [bqlabs/horus#98]
horus used to run fine on Ubuntu 14.04 but since the upgrade on 16.04 I keep getting this error "You probably have selected the wrong camera. Please select another Camera ID". I am sure I select the correct camera since I can see it from VLC. I've noticed that horus seems not to be able to connect to the camera at all since it's indication light is not turning on. I am using the Logitech C270.
Any suggestions as to what may be causing this?

**Comment by yousefalisaad** [comment]
I am struggling with a similar problem and hope that someone help me solve it.

**Comment by blackjec69** [comment]
Same problem, Ubuntu 16.04.1 64-bit
"You probably have selected the wrong camera. Please select another Camera ID" - but camera /dev/video0 present in devices list in settings

**Comment by jsr38** [comment]
I can't debug this right now but I have done in the past.  When horus attempts to initialise the camera, it sets various v4l parameters, including exposure.  If anything is unable to be set correctly, which can be caused, as it was in my case by having the unmodified opencv library code called, it will result in this error.

Also, when I modified source, python will silently fail if it's unable to interpret/compile the source and fall back to the existing pre-built pyc.  

I might check your opencv dependency.

Hope this helps.  Just a thought.

**Comment by jsr38** [comment]
To clarify, check you are calling the project's own modified opencv code.

**Comment by blackjec69** [comment]
Thanks, I try it tomorrow.

**Comment by blackjec69** [comment]
Issue solved.

Horus need modifyed by BQ libopencv* and python-opencv, but ppa:bqopensource/opencv not containt package for 16.04.* - https://launchpad.net/~bqopensource/+archive/ubuntu/opencv

I get source of bqlabs/openvc - https://github.com/bqlabs/opencv - and compile it on my system (without CUDA support - it's detected by cmake but failed during compilation with CUDA 7.5)

Then I copy new python-opencv library **cv2.so** to /usr/lib/python2.7/dist-packages and rename original **/usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so** to cv2.x86_64-linux-gnu.so.OLD

Done :)

**Comment by jsr38** [comment]
Sorry @dkoukoul , I wish I'd spotted your question sooner.  Disclaimer: I'm not a developer, I've just been playing with the code.  I actually have notes of what @blackjec69 did as I had the same problem but sadly haven't posted it on my website yet.  Under construction.

**Comment by leccybill** [comment]
I'm having trouble with same error but on Mac. Reinstalled software and drivers but still not working. Used to at least scan even though scans were useless. Nearly 2 years now and not managed one good scan and this error has put an end to my experiments. Happy to hear from anyone that has made this work who isn't the developer or retailers. Even happier to hear from the developer or support that can help me make this work. Thinking of stripping it for spares.

**Comment by leccybill** [comment]
I'm thinking of offering a reward to anyone not connected with this who can show me a decent scan but surely it shouldn'the come to this. Ok software is open source but you and I paid good money believing we would get results. 2 years of poor scans and now got the camera issue too. Thing is unusable. I'm happy to post my 0 star review wherever I see this sold and I keep searching so I can review it to save others the waste of time this has been. Please please please anyone convince me otherwise.

**Comment by davidedmundson** [comment]
>Then I copy new python-opencv library cv2.so to /usr/lib/python2.7/dist-packages and rename original /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so to cv2.x86_64-linux-gnu.so.OLD

Rather than doing that, adjust your PYTHONPATH to include the directory of the newly installed cv2.so.
